#!/bin/bash

# 读取变量名称
name=$1
dst="$baseDir/${name^}/Model"

# 创建模型路径
mkdir -p $dst

# 创建模型文件
cp $vendorDir/template/Model/Model.php $dst
sed -i "s/{@name}/${name^}/$dst/Model.php"

# 创建Null模型文件
cp $vendorDir/template/Model/NullModel.php $dst
sed -i "s/{@name}/${name^}/$dst/NullModel.php"