#!/bin/bash

function menu {
	echo 
	echo -e "\t\tmarmot-initial\n"
	echo -e "\t使用方法: marmot-initial xxx . 如: marmot-initial News\n"
	echo -e "marmot-initial Options:\n"
	echo -e "--overwrite: 覆盖已经生成的文件\n"
}